// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcuuxyjlqudubjtafqqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjdXV4eWpscXVkdWJqdGFmcXFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxODI3NjEsImV4cCI6MjA2Mzc1ODc2MX0.QHO1BECk60nmudghIdzXxxb8g0ehU53cz4G1l7XGExc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);